security:
  oauth2:
    client:
      access-token-uri: https://graph.facebook.com/oauth/access_token
      authentication-scheme: query
      client-authentication-scheme: form
      client-id: ccc
      client-secret: ccc
      token-name: ccswac
      user-authorization-uri: https://www.facebook.com/v9.0/dialog/oauth
    resource:
      user-info-uri: https://graph.facebook.com/me


