version: '3.1'
services:
   db:
      image: postgres
      environment:
         POSTGRES_DB : product_db
         POSTGRES_PASSWORD: admin
         POSTGRES_USER: postgres
      ports:
         - '5432:5432'