spring :
   application :
      name : EurekaService

server :
   port : 8761

eureka :
   instance :
      virtual-host-name : localhost
   client :
      fetch-registry : false
      register-with-eureka : false
   server:
      wait-time-in-ms-when-sync-empty : 0
      enable-self-preservation : false
