spring:
   resources:
      add-mappings : true
   datasource:
      url: jdbc:postgresql://localhost:5432/product_db
      username: postgres
      password: admin
      configuration:
         maximum-pool : 30
   jpa:
      hibernate:
         default_schema: product
         ddl-auto: create-drop
      generate-ddl : true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            jdbc:
               lob:
                  non_contextual_creation: true
