spring:
   rabbitmq:
     host : localhost
     username: guest
     password : guest
     port : 5672
     template :
        exchange : harunugur.exchange
        routing-key : harunugur.routingkey
        default-receive-queue : harunugur.queue
   main :
      allow-bean-definition-overriding : true
app :
   rabbitmq :
      queue: harunugur.queue
